using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class DialogueManejer : MonoBehaviour
{
    //“­‚¢‚½‚ÉƒZƒbƒg‚·‚é
    public Text Messege;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    /*
    public Text Eat = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Sleep = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Park = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Aquarium = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Shopping = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text PachinAndSlot = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Bortrace = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Bicyclerace = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Horserace = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Lottery = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Pettycrime = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Mediumcrime = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    public Text Hevycrime = null;//“­‚¢‚½‚ÌƒeƒLƒXƒg
    */

    // Start is called before the first frame update
    void Start()
    {
        switch (SceneScript.Action)
        {
            case ActionBackgroundState.Error:
                break;

            case ActionBackgroundState.Work:
                WorkMessege();
                break;

            case ActionBackgroundState.Eat:
                EatMessege();
                break;

            case ActionBackgroundState.Sleep:
                SleepMessege();
                break;

            case ActionBackgroundState.Park:
                ParkMessege();
                break;

            case ActionBackgroundState.Aquarium:
                AquariumMessege();
                break;

            case ActionBackgroundState.Shopping:
                ShoppingMessege();
                break;

            case ActionBackgroundState.PachinkoAndSlot:
                PachinAndSlotMessege();
                break;

            case ActionBackgroundState.Bortrace:
                BortraceMessege();
                break;

            case ActionBackgroundState.Bicyclerace:
                BicycleraceMessege();
                break;

            case ActionBackgroundState.Horserace:
                HorseraceMessege();
                break;

            case ActionBackgroundState.Lottery:
                LotteryMessege();
                break;

            case ActionBackgroundState.Pettycrime:
                PettycrimeMessege();
                break;

            case ActionBackgroundState.Midiumcrime:
                MediumcrimeMessege();
                break;

            case ActionBackgroundState.Heveycrime:
                HevycrimeMessege();
                break;
            default:
                break;
        }
        
    }

    // Update is called once per frame
    void Update()
    {

    }
    
    //ƒ[ƒN‚ÌƒZƒŠƒt‚Ìˆ—‚ğs‚¢‚Ü‚·
    void WorkMessege()
    {
        switch (PlayerState.WorkMoney)
        {
            case int i when i <= 10000:
                Messege.text = ("‚ª‚Á‚Â‚èƒTƒ{‚Á‚Ä" + PlayerState.WorkMoney + "‰~‚µ‚©‰Ò‚°‚Ü‚¹‚ñ‚Å‚µ‚½B" + 
                    "\n ”æ‚ê‚Ü‚µ‚½B@‘Ì—Í[‚P‚O ¸_—Í[‚P‚O‚µ‚Ü‚µ‚½B");
                
                break;

            case int i when i <= 20000:
                Messege.text = ("‚¿‚å‚Á‚ÆƒTƒ{‚Á‚Ä" + PlayerState.WorkMoney + "‰~‚µ‚©‰Ò‚°‚Ü‚¹‚ñ‚Å‚µ‚½B" +
                    "\n ”æ‚ê‚Ü‚µ‚½B@‘Ì—Í[‚P‚O ¸_—Í[‚P‚O‚µ‚Ü‚µ‚½B");
                break;

            case int i when i <= 30000:
                Messege.text = ("^–Ê–Ú‚É“­‚¢‚Ä" + PlayerState.WorkMoney + "‰~‚à‰Ò‚°‚Ü‚µ‚½" +
                    "\n ”æ‚ê‚Ü‚µ‚½B@‘Ì—Í[‚P‚O ¸_—Í[‚P‚O‚µ‚Ü‚µ‚½B");
                break;

            case int i when i <= 40000:
                Messege.text = ("’´Šæ’£‚Á‚Ä“­‚¢‚Ä" + PlayerState.WorkMoney + "‰~‚µ‚©‰Ò‚°‚Ü‚µ‚½" +
                    "\n ”æ‚ê‚Ü‚µ‚½B@‘Ì—Í[‚P‚O ¸_—Í[‚P‚O‚µ‚Ü‚µ‚½B");
                break;
                
            default:
                Messege.text = ("ƒoƒOƒŒƒxƒ‹" + PlayerState.WorkMoney + "‰~‰Ò‚¬‚Ü‚µ‚½B");
                break;
        }
        
    }
    void EatMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1:
                /*
                PlayerState.Physical += 50; //‘Ì—Í‚Ì•ÏX
                PlayerState.Mind += 50; //¸_—Í‚Ì•ÏX
                PlayerState.Money -= 15000;//‚¨‹à‚Ì•ÏX
                Debug.Log("‚‹‰‚ÈH–‚ğ‚µ‚Ü‚µ‚½B");
                */
                Messege.text = ("¡“ú‚Í•±”­‚µ‚Ä‚‹‰‚ÈH–‚ğ‚µ‚Ü‚µ‚½" + 
                    "\n ‚Æ‚Ä‚à‚¨‚¢‚µ‚©‚Á‚½‚Å‚·B@‘Ì—Í{‚T‚O@¸_—Í{‚T‚O@‹à[‚P‚T‚O‚O‚O‰~");

                break;

            case 2:
                /*
                PlayerState.Physical += 30; //‘Ì—Í‚Ì•ÏX
                PlayerState.Mind += 20; //¸_—Í‚Ì•ÏX
                PlayerState.Money -= 3000;//‚¨‹à‚Ì•ÏX
                Debug.Log("•’Ê‚ÌH–‚ğ‚µ‚Ü‚µ‚½B");
                */                
                Messege.text = ("¡“ú‚Í•’Ê‚ÉH–‚ğ‚µ‚Ü‚µ‚½" +
                    "\n ‚¨‚¢‚µ‚©‚Á‚½‚Å‚·B@‘Ì—Í{‚R‚O@¸_—Í{‚Q‚O@‹à[‚P‚O‚O‚O‚O‰~");
                
                break;
            case 3:
                /*
                PlayerState.Physical += 15; //‘Ì—Í‚Ì•ÏX
                PlayerState.Mind += 10; //¸_—Í‚Ì•ÏX
                PlayerState.Money -= 1000;//‚¨‹à‚Ì•ÏX
                Debug.Log("ß–ñ“I‚ÈH–‚ğ‚µ‚Ü‚µ‚½B");
                */
                Messege.text = ("¡“ú‚Í•’Ê‚ÉH–‚ğ‚µ‚Ü‚µ‚½" +
                    "\n ‚¨‚¢‚µ‚©‚Á‚½‚Å‚·B@‘Ì—Í{‚P‚T@¸_—Í{‚P‚O@‹à[‚P‚O‚O‚O‰~");
                break;
            default:
                Debug.Log("ƒoƒO‚Á‚Ä‚¢‚Ü‚·B‘‹}‚É’¼‚µ‚Ä‚­‚¾‚³‚¢");
                break;
        }

    }
    void SleepMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1:
                /*
                PlayerState.Physical += 20; //‘Ì—Í‚Ì•ÏX
                PlayerState.Mind += 30; //¸_—Í‚Ì•ÏX
                Debug.Log("n‡‚Å‚«‚Ü‚µ‚½B");
                */

                Messege.text = ("n‡‚Å‚«‚Ü‚µ‚½" +
                    "\n ‚Æ‚Ä‚àƒXƒbƒLƒŠ‚µ‚Ä‰õ’²‚Å‚·B@‘Ì—Í{‚Q‚O@¸_—Í{‚R‚O");
                break;
            case 2:
                /*
                PlayerState.Physical += 10; //‘Ì—Í‚Ì•ÏX
                PlayerState.Mind += 15; //¸_—Í‚Ì•ÏX                
                Debug.Log("•’Ê‚É–°‚ê‚Ü‚µ‚½");
                */
                Messege.text = ("•’Ê‚ÉQ‚é‚±‚Æ‚ª‚Å‚«‚Ü‚µ‚½" +
                    "\n ƒXƒbƒLƒŠ‚µ‚Ü‚µ‚½B@‘Ì—Í{‚P‚T@¸_—Í{‚P‚O");

                break;
            case 3:
                /*
                PlayerState.Physical += 5; //‘Ì—Í‚Ì•ÏX
                PlayerState.Mind += 10; //¸_—Í‚Ì•ÏX
                Debug.Log("‚ ‚Ü‚è–°‚ê‚Ü‚¹‚ñ‚Å‚µ‚½");
                */
                Messege.text = ("‚ ‚Ü‚è–°‚é‚±‚Æ‚ª‚Å‚«‚Ü‚¹‚ñ‚Å‚µ‚½" +
                    "\n ”æ‚ê‚Í‚¿‚å‚Á‚Æ‚Æ‚ê‚Ü‚µ‚½B@‘Ì—Í{‚T@¸_—Í{‚T");

                break;
            default:
                Debug.Log("ƒoƒO‚Á‚Ä‚¢‚Ü‚·B‘‹}‚É’¼‚µ‚Ä‚­‚¾‚³‚¢");
                break;
        }
    }

    void ParkMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1:
                /*
                PlayerState.Physical -= 15; //‘Ì—Í‚Ì•ÏX
                PlayerState.Mind += 30; //¸_—Í‚Ì•ÏX
                Debug.Log("‰“‚­‚ÌãY—í‚ÈŒö‰€‚É‚¢‚«‚Ü‚µ‚½");
                */
                Messege.text = ("‰“‚­‚ÌãY—í‚ÈŒö‰€‚És‚«‚Ü‚µ‚½" +
                    "\n ãY—í‚ÅS‚ªô‚í‚ê‚Ü‚µ‚½B@‘Ì—Í[‚P‚T@¸_—Í{‚R‚O");

                break;
            case 2:
                /*
                PlayerState.Physical -= 10; //‘Ì—Í‚Ì•ÏX
                PlayerState.Mind += 20; //¸_—Í‚Ì•ÏX                
                Debug.Log("‹ßê‚ÌãY—í‚ÈŒö‰€‚É‚¢‚«‚Ü‚µ‚½");
                */
                Messege.text = ("‹ßê‚ÌãY—í‚ÈŒö‰€‚És‚«‚Ü‚µ‚½" +
                    "\n –‘«‚Å‚«‚Ü‚µ‚½B@‘Ì—Í[‚P‚O@¸_—Í{‚Q‚O");
                
                break;
            case 3:
                /*
                PlayerState.Physical -= 5; //‘Ì—Í‚Ì•ÏX
                PlayerState.Mind += 10; //¸_—Í‚Ì•ÏX
                Debug.Log("‚»‚Ì‚Ö‚ñ‚ğU•à‚µ‚Ü‚µ‚½");
                */
                Messege.text = ("Œü‚©‚¤“r’†‚Å–‘«‚µ‚Ü‚µ‚½B" +
                    "\n U•à‚¶‚á‚ñA‚à‚¤B@‘Ì—Í[‚T@¸_—Í{‚P‚O");

                break;
            default:
                Debug.Log("ƒoƒO‚Á‚Ä‚¢‚Ü‚·B‘‹}‚É’¼‚µ‚Ä‚­‚¾‚³‚¢");
                break;
        }
    }

    void AquariumMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1:
                /*
                PlayerState.Money -= 15000; //Š‹à‚©‚çŒ¸‚ç‚·
                PlayerState.Mind += 50; //¸_—Í‚Ì•ÏX
                Debug.Log("‰“‚­‚Ì’´—L–¼…‘°ŠÙ‚És‚«‚Ü‚µ‚½");
                */
                Messege.text = ("‰“‚­‚Ì’´—L–¼…‘°ŠÙ‚És‚«‚Ü‚µ‚½B" +
                    "\n ãY—í‚ÅŠ´“®‚µ‚Ü‚µ‚½B@¸_—Í{‚T‚O@‹à[‚P‚T‚O‚O‚O‰~");

                break;
            case 2:
                /*
                PlayerState.Money -= 10000; //Š‹à‚©‚çŒ¸‚ç‚·
                PlayerState.Mind += 30; //¸_—Í‚Ì•ÏX
                Debug.Log("‹ßê‚Ì—L–¼…‘°ŠÙ‚És‚«‚Ü‚µ‚½");
                */
                Messege.text = ("‹ßê‚Ì—L–¼‚È…‘°ŠÙ‚És‚«‚Ü‚µ‚½B" +
                    "\n ãY—í‚Å‚µ‚½B@¸_—Í{‚R‚O@‹à[‚P‚O‚O‚O‚O‰~");

                break;
            case 3:
                /*
                PlayerState.Money -= 5000; //Š‹à‚©‚çŒ¸‚ç‚·
                PlayerState.Mind += 15; //¸_—Í‚Ì•ÏX
                Debug.Log("‚È‚ñ‚Æ‚È‚­…‘°ŠÙ‚És‚«‚Ü‚µ‚½");
                */
                Messege.text = ("‚È‚ñ‚Æ‚È‚­…‘°ŠÙ‚És‚«‚Ü‚µ‚½B" +
                    "\n Š¬”\o—ˆ‚Ü‚µ‚½B¸_—Í{‚P‚T@‹à[‚T‚O‚O‚O‰~");

                break;
            default:
                Debug.Log("ƒoƒO‚Á‚Ä‚¢‚Ü‚·B‘‹}‚É’¼‚µ‚Ä‚­‚¾‚³‚¢");
                break;
        }
    }

    void ShoppingMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1:
                /*
                PlayerState.Money -= 50000; //Š‹à‚©‚çŒ¸‚ç‚·
                PlayerState.Ethic += 50; //—Ï—’l‚Ì•ÏX
                Debug.Log("’´”š”ƒ‚¢‚µ‚Ü‚µ‚½");
                */
                Messege.text = ("‚‹‰‚¨‰Ùq‚ğ’´”š”ƒ‚¢‚ğ‚µ‚Ü‚µ‚½B" +
                    "\n –‘«‚µ‚Ü‚µ‚½B—Ï—’l{‚T‚O@‹à[‚T‚O‚O‚O‚O‰~");

                break;
            case 2:
                /*
                PlayerState.Money -= 30000; //Š‹à‚©‚çŒ¸‚ç‚·
                PlayerState.Ethic += 30; //—Ï—’l‚Ì•ÏX
                Debug.Log("”š”ƒ‚¢‚µ‚Ü‚µ‚½");
                */
                Messege.text = ("‚¨‰Ùq‚ğ”š”ƒ‚¢‚µ‚Ü‚µ‚½" +
                    "\n Š¬”\o—ˆ‚Ü‚µ‚½B—Ï—’l{‚R‚O@‹à[‚R‚O‚O‚O‚O‰~");

                break;
            case 3:
                /*
                PlayerState.Money -= 10000; //Š‹à‚©‚çŒ¸‚ç‚·
                PlayerState.Ethic += 15; //—Ï—’l‚Ì•ÏX
                Debug.Log("”ƒ‚¢•¨‚ğ‚µ‚Ü‚µ‚½");
                */
                Messege.text = ("‘Ê‰Ùq‚ğ”š”ƒ‚¢‚µ‚Ü‚µ‚½" +
                    "\n Š¬”\o—ˆ‚Ü‚µ‚½B—Ï—’l{‚P‚T@‹à[‚P‚O‚O‚O‚O‰~");

                break;
            default:
                Debug.Log("ƒoƒO‚Á‚Ä‚¢‚Ü‚·B‘‹}‚É’¼‚µ‚Ä‚­‚¾‚³‚¢");
                break;
        }
    }

    void PachinAndSlotMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1://‘åŸ
                /*
                PlayerState.Addiction += 10;
                PlayerState.Money += 80000;
                Debug.Log("ƒpƒ`ƒ“ƒR‚Å‘åŸ‚¿‚µ‚Ü‚µ‚½");
                */
                Messege.text = ("‚Æ‚ ‚é‰ÈŠw‚Ì’´“d¥–C‚Ìƒpƒ`ƒ“ƒR‚Å‘åŸ‚¿‚µ‚Ü‚µ‚½" +
                    "\n ‚Æ‚Ä‚àŠy‚µ‚©‚Á‚½‚Å‚·B’†“Å’l{‚P‚T@‹à{‚W‚O‚O‚O‚O‰~");
                break;

            case 2://Ÿ‚¿
                /*
                PlayerState.Addiction += 5;
                PlayerState.Money += 40000;
                Debug.Log("ƒpƒ`ƒ“ƒR‚ÅŸ‚¿‚µ‚Ü‚µ‚½");
                */
                Messege.text = ("ƒKƒ“ƒ_ƒ€‚t‚b‚ÅŸ‚¿‚Ü‚µ‚½" +
                    "\n Š¬”\o—ˆ‚Ü‚µ‚½B’†“Å’l{‚P‚O@‹à{‚S‚O‚O‚O‚O‰~");

                break;

            case 3://ƒgƒ“ƒgƒ“
                /*
                PlayerState.Addiction += 3;
                Debug.Log("ƒpƒ`ƒ“ƒR‚Åƒgƒ“ƒgƒ“‚Å‚µ‚½");
                */
                Messege.text = ("µ‚Â‚Ì‘åß‚Q‚Åƒgƒ“ƒgƒ“‚Å‚µ‚½" +
                    "\n ‚Ü‚½Ÿ•‰‚µ‚Ü‚·B’†“Å’l{‚P‚O");

                break;
            case 4://•‰‚¯
                   /*
                   PlayerState.Addiction += 2;
                   PlayerState.Money -= 40000;
                   Debug.Log("ƒpƒ`ƒ“ƒR‚Å•‰‚¯‚Ü‚µ‚½");
                   */
                Messege.text = ("‹S‚ª‚©‚èƒŠƒ[ƒ‚Å•‰‚¯‚Ü‚µ‚½" +
                    "\n B‰÷‚µ‚©‚Á‚½‚Ì‚ÅƒŠƒxƒ“ƒW‚µ‚Ü‚·B’†“Å’l{2@‹à[‚S‚O‚O‚O‚O‰~");

                break;
            case 5://‘å•‰‚¯
                   /*
                   PlayerState.Addiction += 1;
                   PlayerState.Money -= 80000;
                   Debug.Log("ƒpƒ`ƒ“ƒR‚Å‘å•‰‚¯‚Ü‚µ‚½");
                   */
                Messege.text = ("‘åH‚ÌŒ´‚³‚ñ‚Å‘å•‰‚µ‚Ü‚µ‚½B" +
                    "\n “ñ“x‚Æ‚¤‚¿‚Ü‚¹‚ñB’†“Å’l{‚P@‹à[‚W‚O‚O‚O‚O‰~");
                break;


        }
    }

    void BortraceMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1://‘åŸ
                /*
                PlayerState.Addiction += 10;
                PlayerState.Money += 100000;
                */
                Messege.text = ("‘åŒŠ‚É‚©‚¯‚ÄŒ©–“–‚½‚è‚Ü‚µ‚½" +
                    "\n ”’”M‚µ‚½‡‚Å‚µ‚½B’†“Å’l{‚P‚O@‹à{‚P‚O‚O‚O‚O‚O‰~");
                break;

            case 2://Ÿ‚¿
                /*
                    PlayerState.Addiction += 5;
                    PlayerState.Money += 30000;
                */
                Messege.text = ("l‹C‚Ì‚à‚Ì‚É‚©‚¯‚ÄŸ‚¿‚Ü‚µ‚½" +
                    "\n@Šy‚µ‚©‚Á‚½‚Å‚·B’†“Å’l{‚T@‹à{‚R‚O‚O‚O‚O‰~");

                break;

            case 3://ƒgƒ“ƒgƒ“
                /*
                    PlayerState.Addiction += 3;
                */
                Messege.text = ("l‹C‡‚É‚È‚è‚Ü‚µ‚½B" +
                    "\n ‚Ü‚½¡“x—ˆ‚æ‚¤...B’†“Å’l{‚R");

                break;
            case 4://•‰‚¯
                   /*
                    PlayerState.Addiction += 2;
                    PlayerState.Money -= 50000;
                   */
                Messege.text = ("l‹C‡‚ª‚¿‚å‚Á‚Æ‚¸‚ê‚Ü‚µ‚½B" +
                    "\n @‚Ü‚½¡“xA‘åŒŠ‚É‚©‚¯‚Ü‚·B’†“Å’l{2@‹à[‚T‚O‚O‚O‚O‰~");

                break;
            case 5://‘å•‰‚¯
                   /*
                   PlayerState.Addiction += 1;
                   PlayerState.Money -= 100000;
                   */
                Messege.text = ("‚©‚¯‚Ä‚È‚¢‘åŒŠ‡‚É‚È‚è‚Ü‚µ‚½B" +
                    "\n ‚©‚¯‚Ä‚¢‚½‚à‚Ì‘S•”‚ª–³‘Ê‚É‚È‚è‚Ü‚µ‚½B’†“Å’l{‚P@‹à[‚P‚O‚O‚O‚O‚O‰~");
                break;


        }
    }

    void BicycleraceMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1://‘åŸ
                /*
                 * 
                 * 
                 * 
                */
                Messege.text = ("‘åŒŠ‚É‚©‚¯‚ÄŒ©–“–‚½‚è‚Ü‚µ‚½" +
                    "\n ”’”M‚µ‚½‡‚Å‚µ‚½B’†“Å’l{‚P‚O@‹à{‚P‚O‚O‚O‚O‚O‰~");
                break;

            case 2://Ÿ‚¿
                /*
                 *
                 * 
                */
                Messege.text = ("l‹C‚Ì‚à‚Ì‚É‚©‚¯‚ÄŸ‚¿‚Ü‚µ‚½" +
                    "\n@Šy‚µ‚©‚Á‚½‚Å‚·B’†“Å’l{‚T@‹à{‚T‚O‚O‚O‚O‰~");

                break;

            case 3://ƒgƒ“ƒgƒ“
                /*
                   @
                */
                Messege.text = ("l‹C‡‚É‚È‚è‚Ü‚µ‚½B" +
                    "\n ‚Ü‚½¡“x—ˆ‚æ‚¤...B’†“Å’l{‚R");

                break;
            case 4://•‰‚¯
                   /*
                    
                   */
                Messege.text = ("l‹C‡‚ª‚¿‚å‚Á‚Æ‚¸‚ê‚Ü‚µ‚½B" +
                    "\n @‚Ü‚½¡“xA‘åŒŠ‚É‚©‚¯‚Ü‚·B’†“Å’l{2@‹à[‚W‚O‚O‚O‚O‰~");

                break;
            case 5://‘å•‰‚¯
                   /*
                   

                   */
                Messege.text = ("‚©‚¯‚Ä‚È‚¢‘åŒŠ‡‚É‚È‚è‚Ü‚µ‚½B" +
                    "\n ‚©‚¯‚Ä‚¢‚½‚à‚Ì‘S•”‚ª–³‘Ê‚É‚È‚è‚Ü‚µ‚½B’†“Å’l{‚P@‹à[‚P‚T‚O‚O‚O‚O‰~");
                break;


        }
    }

    void HorseraceMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1://‘åŸ
                /*
                PlayerState.Addiction += 10;
                PlayerState.Money += 500000;
                */
                Messege.text = ("‚©‚¯‚Ä‚¢‚½‘åŒŠ‚ªŒ©–“–‚½‚è‚Ü‚µ‚½B" +
                    "\n ‘åŸ‚µ‚Ü‚µ‚½B’†“Å’l{‚P‚O@‹à[‚T‚O‚O‚O‚O‚O‰~");
                break;

            case 2://ƒgƒ“ƒgƒ“
                /*
                PlayerState.Addiction += 5;
                */
                Messege.text = ("l‹C‡’Ê‚è‚É‚È‚è‚Ü‚µ‚½" +
                    "\n ‚¨‹à‚Í‚©‚¯‚½‹àŠz‹A‚Á‚Ä‚«‚Ü‚µ‚½B’†“Å’l{‚T");
                break;

            case 3://•‰‚¯
                /*
                PlayerState.Addiction += 3;
                PlayerState.Money -= 50000;
                */
                Messege.text = ("l‹C‡‚ª‚¿‚å‚Á‚Æ‚©‚í‚è‚Ü‚µ‚½B" +
                    "\n ­‚µ‚©‚¯‚Ä‚¢‚½‚Ì‚Å‘¹‚ğ‚µ‚Ü‚µ‚½B’†“Å’l{‚R@‹à[‚T‚O‚O‚O‚O‰~");
                break;
            case 4://‘å•‰‚¯
                /*
                PlayerState.Addiction += 2;
                PlayerState.Money -= 100000;
                */

                Messege.text = ("‡ˆÊ‚ªr‚ê‚Ä‘åŒŠ‚ÈŒ‹‰Ê‚Æ‚È‚è‚Ü‚µ‚½B" +
                    "\n ‚©‚¯‚Ä‚¢‚½‚à‚Ì‚ª–³‘Ê‚É‚È‚è‚Ü‚µ‚½B’†“Å’l{‚Q@‹à[‚P‚O‚O‚O‚O‚O‰~");
                break;
            case 5://’´•‰‚¯
                /*
                PlayerState.Addiction += 1;
                PlayerState.Money -= 200000;
                */

                Messege.text = ("‡ˆÊ‚ªr‚ê‚Ér‚êA‚©‚¯‚Ä‚È‚¢‘åŒŠ‡‚É‚È‚è‚Ü‚µ‚½B" +
                    "\n ‚©‚¯‚Ä‚¢‚½‚à‚Ì‘S•”‚ª–³‘Ê‚É‚È‚è‚Ü‚µ‚½B’†“Å’l{‚P@‹à[‚Q‚O‚O‚O‚O‚O‰~");
                break;


        }

    }

    void LotteryMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1://Ÿ‚¿
                /*
                PlayerState.Addiction += 100;
                PlayerState.Money += 100000000;
                */
                Messege.text = ("•ó‚­‚¶‚P“™‚ªŒ©–“–‘I‚µ‚Ü‚µ‚½" +
                    "\n l¶—V‚ñ‚Å•é‚ç‚¹‚é‚æ‚¤‚É‚È‚è‚Ü‚µ‚½B’†“Å’l{‚P‚O‚O@‹à{‚P‚O‚O‚O‚O‚O‚O‚O‚O‰~");
                break;

            case 2://•‰‚¯
                /*
                PlayerState.Addiction += 5;
                PlayerState.Money -= 50000;
                */
                Messege.text = ("•¡”“–‘I‚µ‚½‚½‚ßAŠy‚µ‚ß‚Ü‚µ‚½B" +
                    "\n ‚¿‚å‚Á‚Æ‘¹‚ğ‚µ‚Ü‚µ‚½B’†“Å’l{‚T@‹à[‚T‚O‚O‚O‚O‰~");
                break;

            case 3://•‰‚¯
                /*
                PlayerState.Addiction += 10;
                PlayerState.Money -= 100000;
                */
                Messege.text = ("“–‘I”‚ª­‚È‚©‚Á‚½‚Å‚·B" +
                    "\n Œ‹\A‘¹‚ğ‚µ‚Ü‚µ‚½B’†“Å’l{‚P‚O@‹à[‚P‚O‚O‚O‚O‚O‰~");
                break;
            case 4://‘å•‰‚¯
                /*
                PlayerState.Addiction += 20;
                PlayerState.Money -= 500000;
                */
                Messege.text = ("•ó‚­‚¶‚ğ”ƒ‚¢‚İ‚·‚¬‚Ü‚µ‚½B" +
                    "\n ‚ß‚¿‚á‚­‚¿‚á•‰‚¯‚Ü‚µ‚½B’†“Å’l{‚Q‚O@‹à[‚T‚O‚O‚O‚O‚O‰~");
                break;
            case 5://’´‘å•‰‚¯
                /*
                PlayerState.Addiction += 30;
                PlayerState.Money -= 1000000;
                */
                Messege.text = ("‚P‚O‚O–œ‰~•ª”ƒ‚Á‚½‚ª“–‚½‚è‚Ü‚¹‚ñ‚Å‚µ‚½B" +
                    "\n ‹ƒ‚¢‚½GGB’†“Å’l{‚R‚O@‹à[‚P‚O‚O‚O‚O‚O‚O‰~");

                break;

        }
    }

    void PettycrimeMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1://¬Œ÷
                /*
                PlayerState.Ethic -= 5;

                PlayerState.Physical += 10;

                PlayerState.Mind += 10;

                PlayerState.Money += 10000;
                */
                Messege.text = ("–œˆø‚«‚É¬Œ÷‚µ‚Ü‚µ‚½B" +
                    "\n –œˆø‚«‚µ‚½¤•i‚Å‚¨• ‚ğ–c‚ç‚Ü‚¹A“]”„‚µ‚Ä‚¨‹à‚ğ–×‚¯‚Ü‚µ‚½B" +
                    "\n —Ï—’l[‚T@‘Ì—Í{‚P‚O@¸_—Í{‚P‚O@‹à{‚P‚O‚O‚O‚O‰~");

                break;

            case 2://–¢‹
                /*
                PlayerState.Ethic -= 3;
                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("–œˆø‚«‚ğ‚µ‚æ‚¤v‚¢‚Ü‚µ‚½‚ª‚â‚ß‚Ü‚µ‚½B" +
                    "\n ƒJƒƒ‰‚ÌˆÊ’u‚ªâ–­‚¾‚Á‚½‚©‚ç‚Å‚·B" +
                    "\n —Ï—’l[‚R");

                break;

            case 3://¸”s
                /*
                PlayerState.EndingNum = 5;

                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("–œˆø‚«‚É¸”s‚µ‚Ü‚µ‚½B" +
                    "\n ’Ê‚è‚·‚ª‚è‚ÌŒx@‚É•ß‚Ü‚è‚Ü‚µ‚½B");

                break;


        }
    }

    void MediumcrimeMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1://¬Œ÷
                   /*
                   PlayerState.Ethic -= 10;

                   PlayerState.Money += 100000;

                   SceneManager.LoadScene("ResultScene");
                   */
                Messege.text = ("ƒŒƒW‹­“‚É¬Œ÷‚µ‚Ü‚µ‚½B" +
                     "\n ‚¿‚å‚Á‚Æ‚µ‚½‘å‹à‚ğ“¾‚ç‚ê‚Ü‚µ‚½B" +
                     "\n —Ï—’l[‚P‚O@‹à‚P‚O‚O‚O‚O‚O‰~");

                break;

            case 2://–¢‹
                /*
                PlayerState.Ethic -= 5;
                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("Œˆs‚µ‚æ‚¤‚Æ‚µ‚½‚ÉŒx@‚ª‚¢‚Ü‚µ‚½B" +
                    "\n ¡‰ñ‚ÍŒ©‘—‚è‚Ü‚µ‚½B@—Ï—’l[‚T");

                break;

            case 3://–¢‹
                /*
                PlayerState.Ethic -= 5;
                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("ŠÄ‹ƒJƒƒ‰‚ª‘‘å‚³‚ê‚Ä‚¨‚èAìí’Ê‚è‚És‚«‚Ü‚¹‚ñ‚Å‚µ‚½B" +
                    "\n ¡‰ñ‚ÍŒ©‘—‚è‚Ü‚µ‚½B—Ï—’l[‚T");

                break;

            case 4://¸”s
                   /*
                   PlayerState.EndingNum = 5;

                   SceneManager.LoadScene("ResultScene");
                   */
                Messege.text = ("e‚ÌˆÀ‘SƒƒbƒN‚ğŠO‚µ–Y‚ê‚Ü‚µ‚½B" +
                             "\n •ß‚Ü‚è‚Ü‚µ‚½B");
                break;

            case 5://¸”s
                /*
                PlayerState.EndingNum = 5;
                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("“¦‘–“r’†‚Éƒpƒ“ƒN‚µ‚Ü‚µ‚½B" +
                    @@@@ "\n •ß‚Ü‚è‚Ü‚µ‚½B");
                break;
                
        }
    }

    void HevycrimeMessege()
    {
        switch (PlayerState.Luck)
        {
            case 1://¬Œ÷
                /*
                PlayerState.Ethic -= 30;

                PlayerState.Money += 1000000;

                Debug.Log("¬Œ÷‚µ‚Ü‚µ‚½");

                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("ƒ^[ƒQƒbƒg‚Ìn––‚É¬Œ÷‚µ‚Ü‚µ‚½B" +
                     "\n Œ_–ñ‹à‚ğ“¾‚ç‚ê‚Ü‚µ‚½B" +
                     "\n —Ï—’l[‚R‚O@‹à‚P‚O‚O‚O‚O‚O‚O‰~");
                break;

            case 2://–¢‹
                /*
                PlayerState.Ethic -= 10;

                Debug.Log("–¢‹‚ÉI‚í‚è‚Ü‚µ‚½");
                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("ƒ^[ƒQƒbƒg‚ªŒ»‚ê‚Ü‚¹‚ñ‚Å‚µ‚½B" +
                   @@@@  "\n ¡‰ñ‚ÍŒ©‘—‚è‚Ü‚µ‚½B@—Ï—’l[‚P‚O");

                break;

            case 3://¸”s
                /*
                PlayerState.EndingNum = 5;

                Debug.Log("¸”s‚µ‚Ü‚µ‚½");

                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("ƒ^[ƒQƒbƒg‚É•Ô‚è“¢‚¿‚É‚³‚ê‚Ü‚µ‚½B" +
                    @@@@ "\n •ß‚Ü‚è‚Ü‚µ‚½B");

                break;

            case 4://¸”s
                /*
                PlayerState.EndingNum = 5;

                Debug.Log("¸”s‚µ‚Ü‚µ‚½‚Q");
                Debug.Log(PlayerState.EndingNum);

                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("‘_‚Á‚Ä‚¢‚é‚Ì‚ªƒoƒŒ‚Ä‚¢‚Ü‚µ‚½B" +
                             "\n •ß‚Ü‚è‚Ü‚µ‚½");


                break;

            case 5://¸”s
                /*
                PlayerState.EndingNum = 5;

                Debug.Log("¸”s‚µ‚Ü‚µ‚½‚R");
                Debug.Log(PlayerState.EndingNum);

                SceneManager.LoadScene("ResultScene");
                */
                Messege.text = ("n––‚µ‚½‚ÉŒx@‚ÉŒ©‚ç‚ê‚Ä‚¢‚Ü‚µ‚½B" +
                   @@@@  "\n •ß‚Ü‚è‚Ü‚µ‚½B");

                break;

        }
    }




}
